Repository SanaaTeam/TudeeAssistant, pull requests merged in 2025-07, with the labels that each got.

#235 rename homeComponents to component
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/HomeOverviewCard.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/Line.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/TaskCountByStatusCard.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/TaskStatusList.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/Title.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/TopDate.kt
Labels: finish

#234 Refactor/cleanup composable
  app/src/main/java/com/sanaa/tudee_assistant/domain/service/StringProvider.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/DayItem.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/PriorityTag.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/Slider.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/StatusImage.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/TaskStatusCard.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/button/FloatingActionButton.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/button/NegativeButton.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/button/NegativeTextButton.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/button/PrimaryButton.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/designSystem/component/button/SecondaryButton.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/model/SliderUiState.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenUiState.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenViewModel.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/HomeOverviewCard.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/Line.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/TaskCountByStatusCard.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/TaskStatusList.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/Title.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/component/TopDate.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/utils/StringProviderImpl.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/strings.xml
Labels: finish, needs review

#231 refactor category navigate effects
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/category/CategoryEffects.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/category/CategoryInteractionListener.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/category/CategoryScreen.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/category/CategoryScreenUiState.kt
  app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/category/CategoryViewModel.kt
Labels: finish

#220 Add test for CategoryTaskViewModel
  app/src/test/java/com/sanaa/tudee_assistant/presentation/screen/categoryTask/CategoryTaskViewModelTest.kt
Labels: test
